security:
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$bgMA/GJCRlD0hcUt4DcjgeuSrSAsEjb4O.OCpkojRtpK/7IOdYCrC #ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$mxDjM1URQ6sYdn2o2ureUuC.F6xE6sYCrRc/jqqgVbX5BDuI3fSWy #admin
                        roles: 'ROLE_ADMIN'

        mysql_provider:
            entity:
                class: Backend\UserBundle\Entity\User
                property: username

        webservice:
            id: backend.webservice_user_provider

        chain_provider:
            chain:
                providers: [webservice]

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        Backend\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
        Backend\UserBundle\Document\User:
            algorithm: bcrypt
            cost: 12
        Backend\UserBundle\Provider\User\WebserviceUser:
            algorithm: bcrypt
            cost: 12


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            #http_basic: ~
            form_login:
                provider: chain_provider
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }